"""Your message

Revision ID: 0340e02e5053
Revises: b04eb3b09276
Create Date: 2024-03-22 14:24:22.718379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0340e02e5053'
down_revision = 'b04eb3b09276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
