"""Your message

Revision ID: 7ade559a6d32
Revises: 0340e02e5053
Create Date: 2024-03-22 20:08:18.758593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ade559a6d32'
down_revision = '0340e02e5053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
